In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
import matplotlib.pyplot as plt

# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kapaa,US,2022-04-08 02:30:55,22.0752,-159.3190,82.38,72,75,19.57
1,1,Pevek,RU,2022-04-08 02:30:56,69.7008,170.3133,-2.02,82,94,9.13
2,2,Busselton,AU,2022-04-08 02:30:56,-33.6500,115.3333,70.32,78,99,13.65
3,3,Pangnirtung,CA,2022-04-08 02:30:48,66.1451,-65.7125,12.52,95,99,4.00
4,4,Dikson,RU,2022-04-08 02:30:56,73.5069,80.5464,5.58,94,100,11.34
...,...,...,...,...,...,...,...,...,...,...
575,575,Ust-Kuyga,RU,2022-04-08 02:33:44,70.0167,135.6000,11.61,66,82,0.47
576,576,Garden City,US,2022-04-08 02:33:45,42.3256,-83.3310,43.05,70,40,10.36
577,577,Soyo,AO,2022-04-08 02:29:19,-6.1349,12.3689,77.23,89,100,6.51
578,578,Catabola,AO,2022-04-08 02:33:45,-12.1500,17.2833,59.40,96,20,3.09
579,579,Kizlyar,RU,2022-04-08 02:33:45,43.8469,46.7150,45.91,71,91,12.80

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Heatmap of temperature.

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
    
# Assign the figure variable.
fig = gmaps.figure(center=(25, 0),
                   zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=[max(temp, 0) for temp in max_temp],
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Heatmap of percent humidity

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the humidity.
humidity = city_data_df["Humidity"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0),
                   zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=humidity,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

# Add the heat map layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent cloudiness

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the cloudiness.
clouds = city_data_df["Cloudiness"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0),
                   zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=clouds,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

# Add the heat map layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of wind speed

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the wind speed.
wind = city_data_df["Wind Speed"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0),
                   zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations,
                                 weights=wind,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

# Add the heat map layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [10]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kapaa,US,2022-04-08 02:30:55,22.0752,-159.3190,82.38,72,75,19.57
10,10,Cap Malheureux,MU,2022-04-08 02:30:58,-19.9842,57.6142,75.47,87,28,1.01
11,11,Camocim,BR,2022-04-08 02:30:59,-2.9022,-40.8411,76.46,89,82,9.22
13,13,Vaini,TO,2022-04-08 02:30:59,-21.2000,-175.2000,84.36,84,75,5.75
14,14,Makakilo City,US,2022-04-08 02:31:00,21.3469,-158.0858,82.72,51,20,19.57
15,15,Rikitea,PF,2022-04-08 02:31:00,-23.1203,-134.9692,79.12,74,6,15.12
18,18,Guiren,CN,2022-04-08 02:31:01,33.6697,118.1889,76.55,54,0,11.25
19,19,Alofi,NU,2022-04-08 02:31:01,-19.0595,-169.9187,84.09,74,100,13.80
22,22,Taoudenni,ML,2022-04-08 02:31:02,22.6783,-3.9836,78.44,9,0,10.33
27,27,Bengkulu,ID,2022-04-08 02:31:04,-3.8004,102.2655,83.21,63,69,1.92

In [11]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       0
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [12]:
preferred_cities_df.count()

City_ID       180
City          180
Country       180
Date          180
Lat           180
Lng           180
Max Temp      180
Humidity      180
Cloudiness    180
Wind Speed    180
dtype: int64

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

               City Country  Max Temp      Lat       Lng Hotel Name
0             Kapaa      US     82.38  22.0752 -159.3190
10   Cap Malheureux      MU     75.47 -19.9842   57.6142
11          Camocim      BR     76.46  -2.9022  -40.8411
13            Vaini      TO     84.36 -21.2000 -175.2000
14    Makakilo City      US     82.72  21.3469 -158.0858
..              ...     ...       ...      ...       ...        ...
563       Dhidhdhoo      MV     83.71   6.8833   73.1000
571     Port-Gentil      GA     80.42  -0.7193    8.7815
572       Ewa Beach      US     84.15  21.3156 -158.0072
573          Sokoni      TZ     78.66  -6.4333   39.5500
577            Soyo      AO     77.23  -6.1349   12.3689

[180 rows x 6 columns]

In [14]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [15]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print(hotels["results"][0]["name"])
    except (IndexError):
        print("Hotel not found... skipping.")

hotel_df

Sheraton Kauai Coconut Beach Resort
Pereybere Hotel & Spa
Ilha Praia Hotel
Keleti Beach Resort
Marriott's Ko Olina Beach Club
People ThankYou
Suyuan Hotel
Taloa Heights
Hotel not found... skipping.
Grage Hotel Bengkulu
Bonthe Holiday Village
Atlantis Hotel
ibis Styles Mt Isa Verona
DoubleFAG
Finch Bay Galapagos Hotel
Hilo Hawaiian Hotel
Imagination Island
Cititel Penang
Santhi Inn
Scoop Guest House
Tour Eiffel Hotel Benin
INN NEW HORIZON
Hospitality Carnarvon
Hotel Saigon-PT
Aridolf Resort Wellness and Spa
Hotel not found... skipping.
SEGAYA PROPERTY
Tanna Lodge
Maitai Lapita Village Huahine
Pension Oaoa
Villa Enata
La Case Bambou
Bora-Bora Pearl Beach Resort & Spa
Hotel Yugaf Inn Okinawa
Lorengau Harbourside Hotel
Nusa Island Retreat
Hôtel Bon Séjour
Hotel not found... skipping.
The Espiritu Hotel
Shandrani Beachcomber Resort & Spa
Hotel La Ballena Azul
Maqna Hotel by Prasanthi
ProDAF/Diffa
Holiday Inn Express Lompoc, an IHG Hotel
Hotel Kou-Bugny
Expeditions Ténére voyages
Pousada Monte Carmelo O Pão
Kashmiri Hotal
OYO 1577 Hotel Shree Hari Grand
Nancy Montanes Bernardo
pondok pesantren mamba'ul 'ulum selo rejo
Puri Brata
Hospitality Esperance
Paradise Inn
EPIC SANA Luanda
Mercure Padang
Makkah Clock Royal Tower, A Fairmont Hotel
Moevenpick Enshi
Mini Hotel Central
Bam Tourist Hotel
Storyboard Beach Resort
Uruna Bay Retreat
Maringe Lagoon Lodge
Urban Style by Front One
Hotel Atoll Emerald Miyakojima
Osprey Beach Hotel
Ballistic Islet
Aipana Plaza Hotel
Hôtel l’Amitié Bamako
Canopy Tribe
Hotels in Lakshadweep Islands
Hawaiian Princess Resort
Mubashar Quarters
Ramada Hotel & Suites by Wyndham Ballina Byron
Shanti Maurice Resort & Spa
Ha'apai Beach Resort
Quinta Belem
JABIR HOTEL
Cortez Malaga Techy Caroly
Pousada e Restaurante Cheiro e Sabor
Sea Lounge! Bar, Club & Restaurant
Broadwater Mariner Resort
Hotel Tesoro Los Cabos
Hotel not found... skipping.
Lakatoro Palm Lodge
Hotel not found... skipping.
Hotel not found... skipping.
Hôtel Chez Baba
Hotel RIKMAN Continental
Boucan Canot
Kamaneahn Hotel Inc
Penginapan Kim
HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel
Maui Seaside Hotel
Isles Sunset Lodge
Green Park Inn Hotel
Casa Tia Villa
AVK events and catering
Flat Quatro Rodas Olinda
ALETHEIA Appartement Sinnamary
Araguaia Palace Hotel
فندق الدويم
Trinity Plains Tourist Park
Linareva Moorea Beach Resort
Hotel Dakan
Hotel Ambulu Jember
OYO 884 Rumoh PMI Hotel
Hotel Peace Land Ishigakijima
GreenTree Inn Hefei Lujiang County Jinjie 1 Express Hotel
Hotel not found... skipping.
Desert Gardens Hotel - Ayers Rock Resort
Backpackers Inn
CeBlue Villas & Beach Resort
Agapita M. Nicart
Hotel Memory
FELIPA LAODENIO PROPERTY
Hotel not found... skipping.
Pathein Hotel
Foyer ADM
Amaloh Boutique Resort
Aryaduta Hotel
Hotel Festival Plaza Rosarito
IGLESIA EVANGELICA DEL PRINCIPE DE PAZ
Hotel Vitória Palace
Mantra Nelson Bay
STAATS LOGEERGEBOUW TOTNESS
OlusHome
Pousada 100 Passos
Casa Dora, Bubaque
Hôtel Le Dronmi
Grand Palladium Jamaica Resort & Spa
Montana Hotel Syariah
Hotel Flamingo
Hotel not found... skipping.
Nile Palace Hotel
Iftin hotel hobyo
GAASHAAN HOME
degu Shiferaw
Hotel not found... skipping.
Axim Beach Resort And Spa
International Lodge Motel
Bungalow 63
Hotel not found... skipping.
Hotel not found... skipping.
Hotel Fontera Sur
Hôtel Le Lagon
فندق ميس إيجيبت Miss Egypt Hotel
Beso del Viento
Nag Aespen
Lidera
Hotel not found... skipping.
Le Rocher de Tahiti
Seagulls Inn Namatani
Desert Palms Alice Springs
ป่ายางรีสอร์ท
Lamu House
Hotel not found... skipping.
Major Grand
Khách sạn Sài Gòn Bạc Liêu
Hotel not found... skipping.
Camp Pālehua
Hotel not found... skipping.
Roma Zee Guest House Annex
Beach Rotana
Hotel Jardin
Hotel Juba
Yos ega cv
Hotel Recanto Campestre
Holiday Inn Express & Suites Elk Grove Central - Hwy 99, an IHG Hotel
Esquivel's Garden And Resort
Niyama Private Islands Maldives
Syrynity Palace
The Commodore
Sahid Bela Ternate Hotel
Tanjung Kodok Beach Resort
Dhidhoo beach
Fengshui Residence
Base Lodging
Ujamaa Beach Resort
Hotel Mpampa

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Kapaa,US,82.38,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
10,Cap Malheureux,MU,75.47,-19.9842,57.6142,Pereybere Hotel & Spa
11,Camocim,BR,76.46,-2.9022,-40.8411,Ilha Praia Hotel
13,Vaini,TO,84.36,-21.2000,-175.2000,Keleti Beach Resort
14,Makakilo City,US,82.72,21.3469,-158.0858,Marriott's Ko Olina Beach Club
...,...,...,...,...,...,...
563,Dhidhdhoo,MV,83.71,6.8833,73.1000,Dhidhoo beach
571,Port-Gentil,GA,80.42,-0.7193,8.7815,Fengshui Residence
572,Ewa Beach,US,84.15,21.3156,-158.0072,Base Lodging
573,Sokoni,TZ,78.66,-6.4333,39.5500,Ujamaa Beach Resort
577,Soyo,AO,77.23,-6.1349,12.3689,Hotel Mpampa

In [16]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [17]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0),
                   zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations,
                                 weights=max_temp,
                                 dissipating=False,
                                 max_intensity=300,
                                 point_radius=4)

marker_layer = gmaps.marker_layer(locations,
                                  info_box_content=hotel_info)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))